// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type BranchComments struct {
	Comments   []Comment `json:"comments"`
	HasNext    bool      `json:"hasNext"`
	TotalCount int32     `json:"totalCount"`
}

type Comment struct {
	ID        int32           `json:"id"`
	Content   string          `json:"content"`
	PostID    int32           `json:"postID"`
	ParentID  *int32          `json:"parentID,omitempty"`
	AuthorID  int32           `json:"authorID"`
	CreatedAt time.Time       `json:"createdAt"`
	Branch    *BranchComments `json:"branch"`
}

type InputComment struct {
	Content  string `json:"content"`
	PostID   int32  `json:"postID"`
	ParentID *int32 `json:"parentID,omitempty"`
	AuthorID int32  `json:"authorID"`
}

type InputPost struct {
	AuthorID      int32  `json:"authorID"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	AllowComments bool   `json:"allowComments"`
}

type Mutation struct {
}

type Post struct {
	ID            int32           `json:"id"`
	AuthorID      int32           `json:"authorID"`
	Title         string          `json:"title"`
	Content       string          `json:"content"`
	AllowComments bool            `json:"allowComments"`
	CreatedAt     time.Time       `json:"createdAt"`
	Comments      *BranchComments `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
