// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int32
	Content   string
	PostID    int32
	ParentID  pgtype.Int4
	AuthorID  int32
	CreatedAt pgtype.Timestamptz
	Path      []int32
}

type Post struct {
	ID            int32
	Title         string
	Content       string
	AllowComments pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	AuthorID      int32
}
