// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRootComments = `-- name: CountRootComments :one
SELECT COUNT(*) FROM comments
WHERE post_id = $1 AND parent_id IS NULL
`

func (q *Queries) CountRootComments(ctx context.Context, postID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countRootComments, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (content, post_id, parent_id, author_id, path) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING id, content, post_id, parent_id, author_id, created_at, path
`

type CreateCommentParams struct {
	Content  string
	PostID   int32
	ParentID pgtype.Int4
	AuthorID int32
	Path     []int32
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.Content,
		arg.PostID,
		arg.ParentID,
		arg.AuthorID,
		arg.Path,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.Path,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, title, content, allow_comments) 
VALUES ($1, $2, $3, $4) 
RETURNING id, title, content, allow_comments, created_at, author_id
`

type CreatePostParams struct {
	AuthorID      int32
	Title         string
	Content       string
	AllowComments pgtype.Bool
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.AllowComments,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AllowComments,
		&i.CreatedAt,
		&i.AuthorID,
	)
	return i, err
}

const getBranches = `-- name: GetBranches :many
SELECT id, content, post_id, parent_id, author_id, created_at, path FROM comments
WHERE post_id = $1
  AND path[1] = ANY($2::int[])
ORDER BY path, created_at DESC
`

type GetBranchesParams struct {
	PostID  int32
	RootIds []int32
}

func (q *Queries) GetBranches(ctx context.Context, arg GetBranchesParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getBranches, arg.PostID, arg.RootIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentPath = `-- name: GetCommentPath :one
SELECT path FROM comments WHERE id = $1
`

func (q *Queries) GetCommentPath(ctx context.Context, id int32) ([]int32, error) {
	row := q.db.QueryRow(ctx, getCommentPath, id)
	var path []int32
	err := row.Scan(&path)
	return path, err
}

const getCommentsAvailability = `-- name: GetCommentsAvailability :one
SELECT allow_comments FROM posts WHERE id = $1
`

func (q *Queries) GetCommentsAvailability(ctx context.Context, id int32) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, getCommentsAvailability, id)
	var allow_comments pgtype.Bool
	err := row.Scan(&allow_comments)
	return allow_comments, err
}

const getPost = `-- name: GetPost :one
SELECT id, title, content, allow_comments, created_at, author_id FROM posts WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AllowComments,
		&i.CreatedAt,
		&i.AuthorID,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT id, title, content, allow_comments, created_at, author_id FROM posts
`

func (q *Queries) GetPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.AllowComments,
			&i.CreatedAt,
			&i.AuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootComments = `-- name: GetRootComments :many
SELECT id, content, post_id, parent_id, author_id, created_at, path FROM comments
WHERE post_id = $1 AND parent_id IS NULL
ORDER BY path, created_at DESC
LIMIT $2 OFFSET $3
`

type GetRootCommentsParams struct {
	PostID int32
	Limit  int32
	Offset int32
}

func (q *Queries) GetRootComments(ctx context.Context, arg GetRootCommentsParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getRootComments, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentAvailability = `-- name: UpdateCommentAvailability :one
UPDATE posts SET allow_comments = $2 
WHERE id = $1 RETURNING id, title, content, allow_comments, created_at, author_id
`

type UpdateCommentAvailabilityParams struct {
	ID            int32
	AllowComments pgtype.Bool
}

func (q *Queries) UpdateCommentAvailability(ctx context.Context, arg UpdateCommentAvailabilityParams) (Post, error) {
	row := q.db.QueryRow(ctx, updateCommentAvailability, arg.ID, arg.AllowComments)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AllowComments,
		&i.CreatedAt,
		&i.AuthorID,
	)
	return i, err
}

const updateCommentPath = `-- name: UpdateCommentPath :one
UPDATE comments SET path = $2
WHERE id = $1 RETURNING id, content, post_id, parent_id, author_id, created_at, path
`

type UpdateCommentPathParams struct {
	ID   int32
	Path []int32
}

func (q *Queries) UpdateCommentPath(ctx context.Context, arg UpdateCommentPathParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateCommentPath, arg.ID, arg.Path)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.Path,
	)
	return i, err
}
