package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"errors"
	"postsys/internal/adapter"
	"postsys/internal/entity"
	apperr "postsys/internal/errors"
	"postsys/internal/graph/model"
)

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.InputComment) (*model.Comment, error) {
	comment, err := r.service.CreateComment(ctx, adapter.ToServiceInputComment(input))
	if err != nil {
		return nil, handleError(err)
	}

	gqlComment := adapter.ToGraphQLComment(comment)

	r.mu.RLock()
	postSubs := r.subscribersByPosts[gqlComment.PostID]
	r.mu.RUnlock()

	for _, ch := range postSubs {
		select {
		case ch <- &gqlComment:
		default:

		}
	}

	return &gqlComment, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.InputPost) (*model.Post, error) {
	post, err := r.service.CreatePost(ctx, adapter.ToServiceInputPost(input))
	if err != nil {
		return nil, handleError(err)
	}

	qlPost := adapter.ToGraphQLPost(post)
	return &qlPost, nil
}

// UpdatePostCommentsAvailability is the resolver for the updatePostCommentsAvailability field.
func (r *mutationResolver) UpdatePostCommentsAvailability(ctx context.Context, postID int32, userID int32, availability bool) (*model.Post, error) {
	post, err := r.service.UpdateCommentAvailability(ctx, postID, userID, availability)
	if err != nil {
		return nil, handleError(err)
	}

	qlPost := adapter.ToGraphQLPost(post)
	return &qlPost, nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, limit *int32, offset *int32) (*model.BranchComments, error) {
	lim, off := normalizePagination(limit, offset, 10, 0)

	tree, err := r.service.GetCommentsTree(ctx, obj.ID, lim, off)
	if err != nil {
		return nil, handleError(err)
	}

	childrenMap, ok := ctx.Value(childrenMapKey).(map[int32][]entity.Comment)
	if !ok || childrenMap == nil {
		return nil, handleError(apperr.InternalError)
	}

	for k, v := range tree.Children {
		childrenMap[k] = v
	}

	modelComments := make([]model.Comment, len(tree.Roots))
	for i, c := range tree.Roots {
		modelComments[i] = adapter.ToGraphQLComment(c)
	}

	hasNext := off+lim < tree.TotalRoots
	return &model.BranchComments{
		Comments:   modelComments,
		TotalCount: tree.TotalRoots,
		HasNext:    hasNext,
	}, nil
}

// Branch is the resolver for the branch field.
func (r *commentResolver) Branch(ctx context.Context, obj *model.Comment, limit *int32, offset *int32) (*model.BranchComments, error) {
	childrenMap, ok := ctx.Value(childrenMapKey).(map[int32][]entity.Comment)
	if !ok || childrenMap == nil {
		return nil, handleError(apperr.InternalError)
	}

	children, exists := childrenMap[obj.ID]
	if !exists {
		return nil, handleError(apperr.InternalError)
	}

	total := int32(len(children))

	lim, off := normalizePagination(limit, offset, 10, 0)
	end := off + lim
	if end > int32(len(children)) {
		end = int32(len(children))
	}
	page := children[off:end]

	modelComments := make([]model.Comment, len(page))
	for i, c := range page {
		modelComments[i] = adapter.ToGraphQLComment(c)
	}

	hasNext := off+lim < total
	return &model.BranchComments{
		Comments:   modelComments,
		TotalCount: total,
		HasNext:    hasNext,
	}, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]model.Post, error) {
	posts, err := r.service.GetPosts(ctx)
	if err != nil {
		return nil, handleError(err)
	}

	qlPosts := make([]model.Post, len(posts))
	for i := range posts {
		qlPosts[i] = adapter.ToGraphQLPost(posts[i])
	}
	return qlPosts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int32) (*model.Post, error) {
	post, err := r.service.GetPost(ctx, id)
	if err != nil {
		return nil, handleError(err)
	}

	qlPost := adapter.ToGraphQLPost(post)
	return &qlPost, nil
}

// AddComment is the resolver for the addComment field.
func (r *subscriptionResolver) AddComment(ctx context.Context, postID int32) (<-chan *model.Comment, error) {
	ch := make(chan *model.Comment, 10)

	r.mu.Lock()
	r.subscribersByPosts[postID] = append(r.subscribersByPosts[postID], ch)
	r.mu.Unlock()

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		defer r.mu.Unlock()

		subs := r.subscribersByPosts[postID]
		for i, sub := range subs {
			if sub == ch {
				r.subscribersByPosts[postID] = append(subs[:i], subs[i+1:]...)
				break
			}
		}
	}()

	return ch, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

func normalizePagination(limit, offset *int32, defaultLimit, defaultOffset int32) (int32, int32) {
	lim := defaultLimit
	if limit != nil {
		lim = *limit
	}
	off := defaultOffset
	if offset != nil {
		off = *offset
	}
	return lim, off
}

func handleError(err error) error {
	var de *apperr.DomainError
	if errors.As(err, &de) {
		return err
	}

	return apperr.InternalError
}
